name: Build (Gradle)
inputs:
  module-name:
    description: "Gradle module to build"
    required: true
  gpr-username:
    description: "GitHub Package Registry username for authentication"
    required: true
  gpr-token-maven:
    description: "GitHub Package Registry token for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 24

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run Build
      shell: bash
      env:
        GPR_USERNAME: ${{ inputs.gpr-username }}
        GPR_TOKEN: ${{ inputs.gpr-token-maven }}
      run: ./gradlew :${{ inputs.module-name }}:{clean,assemble}
